### ISSUE TITLE
Vector bender error

### ISSUE THREAD

**Issue by mpavon66** [olivierdalang/VectorBender#18]
Unable to make vector bender to work inther Madeira version. here is the errror log:
2019-02-24T10:21:00     WARNING    Traceback (most recent call last):
              File "C:.../QGIS/QGIS3\profiles\default/python/plugins\VectorBender\vectorbender.py", line 151, in run
              self.transformer = LinearTransformer( pairsLayer, restrictToSelection )
              File "C:.../QGIS/QGIS3\profiles\default/python/plugins\VectorBender\vectorbendertransformers.py", line 182, in __init__
              Transformer.__init__(self, pairsLayer, restrictToSelection)
              File "C:.../QGIS/QGIS3\profiles\default/python/plugins\VectorBender\vectorbendertransformers.py", line 22, in __init__
              geom = feature.geometry().asPolyline()
             TypeError: MultiLineString geometry cannot be converted to a polyline. Only single line or curve types are permitted.

**Comment by jaminmelville** [comment]
@mpavon66  I've also encountered this issue too. 
A work around I used while this issue is unresolved is to convert layer using:

`Vector->Geoprocessing Tools->Multipart to singleparts`

Then use new layer as pairs layer for the vector bending.
Hope that helps :smile:

**Comment by baswein** [comment]
Multipart to Single part worked for me as well but only if I save it as a Geopackage. If I save it as a shapefile it doesn't work.

**Comment by rduivenvoorde** [comment]
@mpavon66 @jaminmelville can you maybe add some (small) testing data set, so others can try to reproduce/fix this?

**Comment by trentonyo** [comment]
> @mpavon66 I've also encountered this issue too. A work around I used while this issue is unresolved is to convert layer using:
> 
> `Vector->Geoprocessing Tools->Multipart to singleparts`
> 
> Then use new layer as pairs layer for the vector bending. Hope that helps 😄

For those of us referencing this in the future, you need to convert the bend lines, not the source geometry to be bent
